# Generated by Django 2.0.7 on 2018-08-28 22:39

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre (nom)')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Sous-titre')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('venue', models.CharField(max_length=100, verbose_name='Lieu(x)')),
                ('date_first_day', models.DateField(null=True, verbose_name='Commence le')),
                ('date_last_day', models.DateField(null=True, verbose_name='Finit le ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.upload_path_handler, verbose_name='Image')),
                ('notes', models.CharField(max_length=100, verbose_name='Notes')),
                ('bubble_info', models.TextField(null=True, verbose_name='Bulle info')),
            ],
            options={
                'verbose_name_plural': 'Evénements',
                'verbose_name': 'Evénement',
            },
        ),
        migrations.CreateModel(
            name='Event_Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50, unique=True, verbose_name="Famille d'événements (PAS DE SLASH DANS LE NOM !)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/event_family/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': "Familles d'événements",
                'verbose_name': "Famille d'événements",
            },
        ),
        migrations.AddField(
            model_name='event',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event', to='events.Event_Family'),
        ),
    ]
