# Generated by Django 2.0.7 on 2018-08-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evénement', 'verbose_name_plural': '2. Evénements'},
        ),
        migrations.AlterModelOptions(
            name='event_family',
            options={'verbose_name': "Famille d'événements", 'verbose_name_plural': "1. Familles d'événements"},
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Personne à contacter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bubble_info',
            field=models.TextField(blank=True, null=True, verbose_name='Bulle info'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(blank=True, max_length=100, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous-titre'),
        ),
    ]
