# Generated by Django 2.0.7 on 2018-08-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180828_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne à contacter'),
        ),
    ]
