# Generated by Django 2.2.9 on 2020-01-26 22:36

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190109_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_family',
            name='folder',
            field=models.CharField(blank=True, default='images/event_family/', editable=False, max_length=40, null=True, verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='event_family',
            name='family',
            field=models.CharField(max_length=50, unique=True, verbose_name="Famille d'événements"),
        ),
        migrations.AlterField(
            model_name='event_family',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.upload_path_handler, verbose_name='Image'),
        ),
    ]
