# Generated by Django 2.0.7 on 2019-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/news/', verbose_name='PDF'),
        ),
    ]
