# Generated by Django 2.2.9 on 2020-02-09 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Texte'),
        ),
    ]
