# Generated by Django 2.0.7 on 2018-08-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/activity/animation/', verbose_name='Image')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Animation',
                'verbose_name_plural': '2. Animations',
            },
        ),
        migrations.CreateModel(
            name='Activity_Animation_Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled_friendly', models.BooleanField(default=None, verbose_name='Accessible handicap')),
                ('new', models.BooleanField(default=None, verbose_name='Nouveau')),
                ('available_in_both_cities', models.BooleanField(default=None, verbose_name='Existe à M. et à C.')),
                ('flash', models.CharField(blank=True, max_length=50, null=True, verbose_name='Info flash')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('rate_resident_1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarif 1 MC - Désignation ')),
                ('rate_resident_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif 1 MC - €')),
                ('rate_resident_2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarif 2 MC - Désignation ')),
                ('rate_resident_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif 2 MC - €')),
                ('rate_non_resident_1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarif 1 hors MC - Désignation ')),
                ('rate_non_resident_1', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif 1 hors MC - €')),
                ('rate_non_resident_2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarif 2 hors MC - Désignation ')),
                ('rate_non_resident_2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tarif 2 hors MC - €')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes particulières')),
            ],
            options={
                'verbose_name': 'Animation - Créneau',
                'verbose_name_plural': '3. Animation - Créneaux',
            },
        ),
        migrations.CreateModel(
            name='Activity_Animation_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_type', models.CharField(max_length=100, verbose_name="Type d'animation")),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/activity/animation_type', verbose_name='Image')),
            ],
            options={
                'verbose_name': "Animation - Type d'animation",
                'verbose_name_plural': "1. Animations - Types d'animation",
            },
        ),
        migrations.CreateModel(
            name='Age_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_class', models.CharField(max_length=100, verbose_name="Classe d'age")),
            ],
            options={
                'verbose_name': "Age - Classe d'ages",
                'verbose_name_plural': "B. Age - Classes d'ages",
            },
        ),
        migrations.CreateModel(
            name='Age_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.IntegerField(verbose_name='Age minimum')),
                ('age_max', models.IntegerField(verbose_name='Age maximum')),
                ('age_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Age_Group', to='activities.Age_Class')),
            ],
            options={
                'verbose_name': "Age - Groupe d'ages",
                'verbose_name_plural': "C. Age - Groupes d'ages",
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'G. Villes',
            },
        ),
        migrations.CreateModel(
            name='Elements_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('TRAININGCOURSE', 'TRAININGCOURSE'), ('EVENT', 'EVENT')], max_length=50, verbose_name="Type d'élément")),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Label')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/event_type', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Eléments - Type',
                'verbose_name_plural': 'Z. Eléments - Types',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('initials', models.CharField(max_length=10, null=True, verbose_name='Initiales')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='images/hosts/', verbose_name='Image')),
                ('resume', models.TextField(null=True, verbose_name='Présentation')),
            ],
            options={
                'verbose_name': 'Animateur',
                'verbose_name_plural': 'E. Animateurs',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100, verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'D. Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20, verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'A. Périodes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'I. Salles',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('street_nb', models.CharField(blank=True, max_length=20, verbose_name='N°')),
                ('street_name', models.CharField(max_length=200, verbose_name='Rue')),
                ('postcode', models.IntegerField(verbose_name='Code Postal')),
                ('iframe_url_map', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Google Iframe')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Venue', to='activities.City')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'H. Lieux',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=10, verbose_name='Jour')),
            ],
            options={
                'verbose_name': 'Jour',
                'verbose_name_plural': 'F. Jours',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Room', to='activities.Venue'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Age_Group'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Activity_Animation'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Weekday'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='Activity', to='activities.Host'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Level'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Period'),
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Activity', to='activities.Room'),
        ),
        migrations.AddField(
            model_name='activity_animation',
            name='animation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Animation', to='activities.Activity_Animation_Type'),
        ),
    ]
