# Generated by Django 2.0.7 on 2018-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_animation_slot',
            name='available_in_both_cities',
        ),
        migrations.RemoveField(
            model_name='activity_animation_slot',
            name='disabled_friendly',
        ),
        migrations.RemoveField(
            model_name='activity_animation_slot',
            name='new',
        ),
        migrations.AddField(
            model_name='activity_animation',
            name='available_in_both_cities',
            field=models.BooleanField(default=None, verbose_name='Existe à M. et à C.'),
        ),
        migrations.AddField(
            model_name='activity_animation',
            name='disabled_friendly',
            field=models.BooleanField(default=None, verbose_name='Accessible handicap'),
        ),
        migrations.AddField(
            model_name='activity_animation',
            name='new',
            field=models.BooleanField(default=None, verbose_name='Nouveau'),
        ),
    ]
