# Generated by Django 2.0.7 on 2018-08-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180825_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_animation_type',
            name='notes',
            field=models.TextField(null=True, verbose_name='Notes spécifiques'),
        ),
        migrations.AlterField(
            model_name='activity_animation',
            name='available_in_both_cities',
            field=models.BooleanField(default=None, verbose_name='Existe à Mauguio ET à Carnon'),
        ),
        migrations.AlterField(
            model_name='activity_animation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity_animation_type',
            name='description',
            field=models.TextField(null=True, verbose_name='Description générale'),
        ),
    ]
