# Generated by Django 2.0.7 on 2018-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180825_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_animation_type',
            name='notes',
        ),
        migrations.AddField(
            model_name='activity_animation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes spécifiques (certif. médical, license, ...)'),
        ),
        migrations.AlterField(
            model_name='activity_animation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description générale'),
        ),
        migrations.AlterField(
            model_name='activity_animation_type',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
