# Generated by Django 2.0.7 on 2018-08-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180825_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity_animation_slot',
            options={'verbose_name': 'Animation - Créneau', 'verbose_name_plural': '3. Animations - Créneaux'},
        ),
        migrations.AddField(
            model_name='activity_animation_slot',
            name='new',
            field=models.BooleanField(default=None, verbose_name='Nouveau'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='elements_type',
            name='element_type',
            field=models.CharField(choices=[('ACTIVITY', 'ACTIVITY'), ('WORKSHOP', 'WORKSHOP'), ('EVENT', 'EVENT')], max_length=50, verbose_name="Type d'élément"),
        ),
    ]
