# Generated by Django 2.0.7 on 2018-08-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20180825_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Slot', to='activities.Age_Group'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Slot', to='activities.Activity_Animation'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Slot', to='activities.Weekday'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='host',
            field=models.ManyToManyField(blank=True, related_name='Slot', to='activities.Host'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Slot', to='activities.Level'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Slot', to='activities.Period'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Slot', to='activities.Room'),
        ),
    ]
