# Generated by Django 2.0.7 on 2018-08-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20180826_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_non_resident_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tarif 1 hors MC - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_non_resident_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tarif 2 hors MC - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_resident_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tarif 1 MC - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_resident_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tarif 2 MC - €'),
        ),
    ]
