# Generated by Django 2.0.7 on 2018-08-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20180826_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la Salle'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_nb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de la Salle'),
        ),
    ]
