# Generated by Django 2.0.7 on 2018-08-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20180826_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom/Désignation'),
        ),
    ]
