# Generated by Django 2.0.7 on 2018-08-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20180826_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=100, unique=True, verbose_name='Niveau'),
        ),
    ]
