# Generated by Django 2.0.7 on 2018-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20180828_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_non_resident_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hors MC - Tarif 1 - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_non_resident_1_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hors MC - Tarif 1 - Désignation '),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_non_resident_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hors MC - Tarif 2 - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_non_resident_2_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hors MC - Tarif 2 - Désignation '),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_resident_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='MC - Tarif 1 - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_resident_1_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MC - Tarif 1 - Désignation '),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_resident_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='MC - Tarif 2 - €'),
        ),
        migrations.AlterField(
            model_name='activity_animation_slot',
            name='rate_resident_2_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='MC - Tarif 2  - Désignation '),
        ),
    ]
