# Generated by Django 2.0.7 on 2018-08-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_animation_type',
            name='animation_type',
            field=models.CharField(max_length=100, verbose_name="Type d'animation (PAS DE SLASH DANS LE NOM !)"),
        ),
    ]
