# Generated by Django 2.0.7 on 2018-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20180828_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop_animation_slot',
            name='date_of_the_first_day',
            field=models.DateField(null=True, verbose_name='Date du premier jour'),
        ),
    ]
