# Generated by Django 2.0.7 on 2018-10-22 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0016_activity_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegistrationOrder', to='activities.Activity_Animation_Slot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegistrationOrder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paiements',
                'verbose_name': 'Paiement',
            },
        ),
    ]
