# Generated by Django 2.0.7 on 2019-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files_Pseudostatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Fichier - Nom')),
                ('file_code', models.CharField(max_length=4, verbose_name='Fichier - Code')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/documents/', verbose_name='Fichier - PDF')),
            ],
            options={
                'verbose_name': 'Documents',
                'verbose_name_plural': '1. Documents',
            },
        ),
    ]
