# Generated by Django 2.0.7 on 2019-01-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190110_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_cr',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name="Ordre d'apparition"),
        ),
        migrations.AlterField(
            model_name='files_pseudostatic',
            name='file_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Fichier - Code'),
        ),
        migrations.AlterField(
            model_name='files_pseudostatic',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fichier - Nom'),
        ),
    ]
