# Generated by Django 2.2.9 on 2020-01-26 18:52

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20190110_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_cr',
            name='folder',
            field=models.CharField(blank=True, default='documents-CR', max_length=40, null=True, verbose_name='Folder'),
        ),
        migrations.AddField(
            model_name='files_pseudostatic',
            name='folder',
            field=models.CharField(blank=True, default='documents', max_length=40, null=True, verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='files_cr',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_path_handler, verbose_name='Fichier - PDF'),
        ),
        migrations.AlterField(
            model_name='files_pseudostatic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_path_handler, verbose_name='Fichier - PDF'),
        ),
    ]
