# Generated by Django 2.2.9 on 2020-01-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20200126_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_cr',
            name='folder',
            field=models.CharField(blank=True, default='documents-CR', editable=False, max_length=40, null=True, verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='files_pseudostatic',
            name='folder',
            field=models.CharField(blank=True, default='documents', editable=False, max_length=40, null=True, verbose_name='Folder'),
        ),
    ]
