# Generated by Django 2.0.7 on 2019-01-10 22:58

from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre (nom)')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Sous-titre')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('venue', models.CharField(max_length=100, verbose_name='Lieu(x)')),
                ('date_and_time', models.CharField(max_length=200, null=True, verbose_name='Date(s) & Heure(s)')),
                ('date_first_day', models.DateField(null=True, verbose_name='Commence le')),
                ('date_last_day', models.DateField(null=True, verbose_name='Finit le ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=social.models.upload_path_handler, verbose_name='Image')),
                ('notes', models.CharField(blank=True, max_length=100, verbose_name='Notes')),
                ('bubble_info', models.TextField(blank=True, null=True, verbose_name='Bulle info')),
                ('contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne à contacter')),
                ('rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarifs')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/socials/', verbose_name='PDF')),
            ],
            options={
                'verbose_name_plural': '2. Vivre Ensemble - Ateliers',
                'verbose_name': 'Atelier',
            },
        ),
        migrations.CreateModel(
            name='Social_Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50, unique=True, verbose_name="Famille d'événements (PAS DE SLASH DANS LE NOM !)")),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/social_family/', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': "1. Vivre Ensembe - Famille d'Ateliers",
                'verbose_name': "Famille d'Ateliers",
            },
        ),
        migrations.AddField(
            model_name='social',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Social', to='social.Social_Family'),
        ),
    ]
