# Generated by Django 2.2.9 on 2020-02-09 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200126_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
    ]
