# Generated by Django 2.0.7 on 2019-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=100, verbose_name='Diapo - Titre')),
                ('slide_subtitle', models.CharField(max_length=4, verbose_name='Diapo - Sous titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/carousel', verbose_name='Diapo - Image')),
            ],
            options={
                'verbose_name_plural': 'Caroussel',
                'verbose_name': '1. Diapositives',
            },
        ),
    ]
