# Generated by Django 2.0.7 on 2019-01-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'Diapositive', 'verbose_name_plural': 'Caroussel'},
        ),
        migrations.AlterField(
            model_name='slides',
            name='slide_subtitle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diapo - Sous titre'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='slide_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Diapo - Titre'),
        ),
    ]
