# Generated by Django 2.0.7 on 2019-01-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_auto_20190109_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'Diapositive', 'verbose_name_plural': 'Caroussel (Bandeau défilant)'},
        ),
    ]
