# Generated by Django 2.2.9 on 2020-03-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0007_auto_20200301_1632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='PagePseudoStatic',
        ),
    ]
