# Generated by Django 2.2.9 on 2020-03-01 19:59

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0008_auto_20200301_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fichier - Nom')),
                ('file_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Fichier - Code')),
                ('folder', models.CharField(blank=True, default='documents', editable=False, max_length=40, null=True, verbose_name='Folder')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.upload_path_handler, verbose_name='Fichier - PDF')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagefile', to='views.PagePseudoStatic')),
            ],
            options={
                'verbose_name': 'Documents',
                'verbose_name_plural': '3. Documents - Pages',
            },
        ),
    ]
