# Generated by Django 2.2.9 on 2020-03-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0010_auto_20200301_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'verbose_name': 'Diapositive', 'verbose_name_plural': '1. Page principale - Bandeau défilant'},
        ),
    ]
