# Generated by Django 2.2.9 on 2020-03-14 21:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0011_auto_20200310_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('info', 'INFO (Bleu)'), ('success', 'POSITIF (Vert)'), ('warning', 'ATTENTION (Orange)'), ('danger', 'DANGER (Rouge)')], default='info', max_length=50, null=True, verbose_name='Couleur')),
                ('message', ckeditor.fields.RichTextField(null=True, verbose_name='Message')),
                ('order', models.IntegerField(null=True, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': '2. Page Principale - Messages Importants',
            },
        ),
        migrations.AlterModelOptions(
            name='pagefile',
            options={'verbose_name': 'Documents', 'verbose_name_plural': '4. Pages - Documents'},
        ),
        migrations.AlterModelOptions(
            name='pagepseudostatic',
            options={'verbose_name': 'Page', 'verbose_name_plural': '3. Pages - Texte'},
        ),
    ]
